# Generated by Django 2.2.2 on 2019-08-09 02:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contract_excel', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Harmonized_System',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('custom', models.CharField(max_length=20)),
                ('goods_en_name', models.CharField(max_length=60)),
                ('goods_zh_name', models.CharField(max_length=60)),
                ('product_code', models.CharField(max_length=40)),
                ('goods_code', models.CharField(max_length=40)),
                ('property', models.CharField(max_length=100)),
                ('hs_code', models.CharField(max_length=20)),
                ('hs_name', models.TextField()),
                ('note', models.TextField()),
            ],
            options={
                'verbose_name': 'HS编码信息',
                'verbose_name_plural': 'HS编码信息',
                'db_table': 'hs_info',
            },
        ),
    ]
