# Generated by Django 2.2.2 on 2019-08-09 03:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contract_excel', '0002_harmonized_system'),
    ]

    operations = [
        migrations.AlterField(
            model_name='harmonized_system',
            name='custom',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='harmonized_system',
            name='goods_code',
            field=models.CharField(blank=True, max_length=40),
        ),
        migrations.AlterField(
            model_name='harmonized_system',
            name='goods_en_name',
            field=models.CharField(blank=True, max_length=60),
        ),
        migrations.AlterField(
            model_name='harmonized_system',
            name='goods_zh_name',
            field=models.CharField(blank=True, max_length=60),
        ),
        migrations.AlterField(
            model_name='harmonized_system',
            name='hs_code',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='harmonized_system',
            name='hs_name',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='harmonized_system',
            name='note',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='harmonized_system',
            name='product_code',
            field=models.CharField(blank=True, max_length=40),
        ),
        migrations.AlterField(
            model_name='harmonized_system',
            name='property',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
