# Generated by Django 2.2.2 on 2019-08-09 03:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contract_excel', '0003_auto_20190809_1139'),
    ]

    operations = [
        migrations.AlterField(
            model_name='harmonized_system',
            name='goods_en_name',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AlterField(
            model_name='harmonized_system',
            name='goods_zh_name',
            field=models.CharField(blank=True, max_length=150),
        ),
    ]
