# Generated by Django 2.2.2 on 2020-03-10 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contract_excel', '0004_auto_20190809_1147'),
    ]

    operations = [
        migrations.CreateModel(
            name='Harmonized_System_Customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('custom', models.CharField(blank=True, max_length=20)),
                ('goods_code', models.CharField(blank=True, max_length=40)),
                ('goods_zh_name', models.CharField(blank=True, max_length=150)),
                ('part_num', models.CharField(blank=True, max_length=40)),
                ('goods_en_name', models.CharField(blank=True, max_length=150)),
                ('subull_crapidiary', models.CharField(blank=True, max_length=40)),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=10)),
                ('hs_code', models.CharField(blank=True, max_length=20)),
                ('hs_name', models.TextField(blank=True)),
                ('contract_num', models.CharField(blank=True, max_length=30)),
                ('purchase_year', models.CharField(blank=True, max_length=4)),
            ],
            options={
                'verbose_name': 'HS客户编码信息',
                'verbose_name_plural': 'HS客户编码信息',
                'db_table': 'hs_info_cunstomer',
            },
        ),
    ]
