# Generated by Django 2.2.2 on 2020-03-10 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contract_excel', '0005_harmonized_system_customer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='harmonized_system_customer',
            name='purchase_year',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AlterModelTable(
            name='harmonized_system_customer',
            table='hs_info_new',
        ),
    ]
