# Generated by Django 2.2.2 on 2020-03-10 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contract_excel', '0008_auto_20200310_1657'),
    ]

    operations = [
        migrations.AlterField(
            model_name='harmonized_system_customer',
            name='unit_price',
            field=models.DecimalField(decimal_places=3, max_digits=6),
        ),
    ]
