# Generated by Django 2.2.2 on 2020-03-11 03:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contract_excel', '0015_auto_20200311_1021'),
    ]

    operations = [
        migrations.AlterField(
            model_name='harmonized_system_customer',
            name='unit_price',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=15),
        ),
    ]
