# Generated by Django 2.2.2 on 2019-07-30 07:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contract_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='user',
            table='user',
        ),
    ]
