# Generated by Django 2.2.2 on 2019-07-31 00:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contract_app', '0002_auto_20190730_1521'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(max_length=200),
        ),
    ]
