# Generated by Django 2.2.2 on 2019-08-02 01:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contract_app', '0003_auto_20190731_0842'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name_plural': '注册用户管理'},
        ),
    ]
